# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 211, 71))
        self.groupBox.setObjectName("groupBox")
        self.textEditClientAppend = QtWidgets.QTextEdit(self.groupBox)
        self.textEditClientAppend.setGeometry(QtCore.QRect(10, 30, 141, 31))
        self.textEditClientAppend.setObjectName("textEditClientAppend")
        self.pushButtonAddClient = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonAddClient.setGeometry(QtCore.QRect(160, 30, 41, 31))
        self.pushButtonAddClient.setObjectName("pushButtonAddClient")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 0, 591, 551))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEditEnter = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEditEnter.setGeometry(QtCore.QRect(10, 490, 501, 41))
        self.textEditEnter.setTabChangesFocus(False)
        self.textEditEnter.setObjectName("textEditEnter")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(520, 490, 61, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidgetChat = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidgetChat.setGeometry(QtCore.QRect(10, 20, 571, 461))
        self.tabWidgetChat.setObjectName("tabWidgetChat")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEditChat = QtWidgets.QTextEdit(self.tab)
        self.textEditChat.setGeometry(QtCore.QRect(10, 10, 541, 411))
        self.textEditChat.setReadOnly(True)
        self.textEditChat.setObjectName("textEditChat")
        self.tabWidgetChat.addTab(self.tab, "")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 201, 231))
        self.groupBox_3.setObjectName("groupBox_3")
        self.listWidgetContacts = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidgetContacts.setGeometry(QtCore.QRect(10, 30, 181, 151))
        self.listWidgetContacts.setObjectName("listWidgetContacts")
        self.pushButtonRemove = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonRemove.setGeometry(QtCore.QRect(120, 190, 71, 23))
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.pushButtonChat = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButtonChat.setGeometry(QtCore.QRect(10, 190, 75, 23))
        self.pushButtonChat.setObjectName("pushButtonChat")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 330, 201, 221))
        self.groupBox_4.setObjectName("groupBox_4")
        self.listWidgetOnline = QtWidgets.QListWidget(self.groupBox_4)
        self.listWidgetOnline.setGeometry(QtCore.QRect(10, 50, 181, 151))
        self.listWidgetOnline.setObjectName("listWidgetOnline")
        self.pushButtonOnlineRefresh = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonOnlineRefresh.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButtonOnlineRefresh.setObjectName("pushButtonOnlineRefresh")
        self.pushButtonOnlineRemove = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButtonOnlineRemove.setGeometry(QtCore.QRect(120, 20, 75, 23))
        self.pushButtonOnlineRemove.setObjectName("pushButtonOnlineRemove")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 858, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidgetChat.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Add Client"))
        self.pushButtonAddClient.setText(_translate("MainWindow", "Add"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Chat"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.tabWidgetChat.setTabText(self.tabWidgetChat.indexOf(self.tab), _translate("MainWindow", "All"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Contacts"))
        self.pushButtonRemove.setText(_translate("MainWindow", "Remove"))
        self.pushButtonChat.setText(_translate("MainWindow", "Chat"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Online"))
        self.pushButtonOnlineRefresh.setText(_translate("MainWindow", "Refresh"))
        self.pushButtonOnlineRemove.setText(_translate("MainWindow", "Remove"))

